# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_block_design_cpp <- function(B, nR, dummy_block) {
    .Call('_GreedyExperimentalDesign_generate_block_design_cpp', PACKAGE = 'GreedyExperimentalDesign', B, nR, dummy_block)
}

compute_distance_matrix_cpp <- function(X) {
    .Call('_GreedyExperimentalDesign_compute_distance_matrix_cpp', PACKAGE = 'GreedyExperimentalDesign', X)
}

shuffle_cpp <- function(w, seed) {
    .Call('_GreedyExperimentalDesign_shuffle_cpp', PACKAGE = 'GreedyExperimentalDesign', w, seed)
}

create_all_ys_cpp <- function(pCs, pTs, W, two_n, nY) {
    .Call('_GreedyExperimentalDesign_create_all_ys_cpp', PACKAGE = 'GreedyExperimentalDesign', pCs, pTs, W, two_n, nY)
}

all_elements_same_cpp <- function(vec) {
    .Call('_GreedyExperimentalDesign_all_elements_same_cpp', PACKAGE = 'GreedyExperimentalDesign', vec)
}

gen_pm_designs_cpp <- function(indicies_pairs, n, r) {
    .Call('_GreedyExperimentalDesign_gen_pm_designs_cpp', PACKAGE = 'GreedyExperimentalDesign', indicies_pairs, n, r)
}

compute_avg_abs_rijss_left <- function(Rij) {
    .Call('_GreedyExperimentalDesign_compute_avg_abs_rijss_left', PACKAGE = 'GreedyExperimentalDesign', Rij)
}

