// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_block_design_cpp
List generate_block_design_cpp(int B, int nR, NumericVector dummy_block);
RcppExport SEXP _GreedyExperimentalDesign_generate_block_design_cpp(SEXP BSEXP, SEXP nRSEXP, SEXP dummy_blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type nR(nRSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dummy_block(dummy_blockSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_block_design_cpp(B, nR, dummy_block));
    return rcpp_result_gen;
END_RCPP
}
// compute_distance_matrix_cpp
NumericMatrix compute_distance_matrix_cpp(NumericMatrix X);
RcppExport SEXP _GreedyExperimentalDesign_compute_distance_matrix_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_distance_matrix_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_cpp
NumericVector shuffle_cpp(NumericVector w, unsigned int seed);
RcppExport SEXP _GreedyExperimentalDesign_shuffle_cpp(SEXP wSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_cpp(w, seed));
    return rcpp_result_gen;
END_RCPP
}
// create_all_ys_cpp
LogicalMatrix create_all_ys_cpp(NumericVector pCs, NumericVector pTs, NumericMatrix W, int two_n, int nY);
RcppExport SEXP _GreedyExperimentalDesign_create_all_ys_cpp(SEXP pCsSEXP, SEXP pTsSEXP, SEXP WSEXP, SEXP two_nSEXP, SEXP nYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pCs(pCsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pTs(pTsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type two_n(two_nSEXP);
    Rcpp::traits::input_parameter< int >::type nY(nYSEXP);
    rcpp_result_gen = Rcpp::wrap(create_all_ys_cpp(pCs, pTs, W, two_n, nY));
    return rcpp_result_gen;
END_RCPP
}
// all_elements_same_cpp
bool all_elements_same_cpp(NumericVector vec);
RcppExport SEXP _GreedyExperimentalDesign_all_elements_same_cpp(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(all_elements_same_cpp(vec));
    return rcpp_result_gen;
END_RCPP
}
// gen_pm_designs_cpp
NumericMatrix gen_pm_designs_cpp(NumericMatrix indicies_pairs, int n, int r);
RcppExport SEXP _GreedyExperimentalDesign_gen_pm_designs_cpp(SEXP indicies_pairsSEXP, SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type indicies_pairs(indicies_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_pm_designs_cpp(indicies_pairs, n, r));
    return rcpp_result_gen;
END_RCPP
}
// compute_avg_abs_rijss_left
NumericVector compute_avg_abs_rijss_left(NumericMatrix Rij);
RcppExport SEXP _GreedyExperimentalDesign_compute_avg_abs_rijss_left(SEXP RijSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Rij(RijSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_avg_abs_rijss_left(Rij));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GreedyExperimentalDesign_generate_block_design_cpp", (DL_FUNC) &_GreedyExperimentalDesign_generate_block_design_cpp, 3},
    {"_GreedyExperimentalDesign_compute_distance_matrix_cpp", (DL_FUNC) &_GreedyExperimentalDesign_compute_distance_matrix_cpp, 1},
    {"_GreedyExperimentalDesign_shuffle_cpp", (DL_FUNC) &_GreedyExperimentalDesign_shuffle_cpp, 2},
    {"_GreedyExperimentalDesign_create_all_ys_cpp", (DL_FUNC) &_GreedyExperimentalDesign_create_all_ys_cpp, 5},
    {"_GreedyExperimentalDesign_all_elements_same_cpp", (DL_FUNC) &_GreedyExperimentalDesign_all_elements_same_cpp, 1},
    {"_GreedyExperimentalDesign_gen_pm_designs_cpp", (DL_FUNC) &_GreedyExperimentalDesign_gen_pm_designs_cpp, 3},
    {"_GreedyExperimentalDesign_compute_avg_abs_rijss_left", (DL_FUNC) &_GreedyExperimentalDesign_compute_avg_abs_rijss_left, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_GreedyExperimentalDesign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
